apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv1
spec:
  # 指定 PV 的容量为1Gi
  capacity:
    storage: 1Gi
  # 指定访问模式
  accessModes:
    # PV 能以 readwrite 模式 mount 到单个节点
    - ReadWriteOnce
  # 指定 PV 的回收策略，即 PVC 资源释放后的事件，recycle (不建议，使用动态供给代替)删除 PVC 的所有文件
  persistentVolumeReclaimPolicy: Recycle
  # 指定 PV 的 class 为 mynfs，相当于为 PV 分类，PVC 将指定 class 申请 PV
  storageClassName: mynfs
  # 指定 PV 为 nfs 服务器上对应的目录
  nfs:
    path: /data/nfs
    server: 192.168.20.10
    