# cat pvjob.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: pvjob
spec:
  template:
    spec:
      containers:
        - name: bbox1
          image: busybox
          command: ["/bin/sh","-c","echo 'hello pv' > /mydata/hello"]
          volumeMounts:
            - mountPath: "/mydata"
              name: mydata
      restartPolicy: Never
      volumes:
        - name: mydata
          persistentVolumeClaim:
            claimName: nfspvc1